dataset: Sim_Demand_Design_Vector_PCAOnly_IV
output_dir: "."
use_gpu: false
rho: 0.5
n_repeat: 20
representation_sd: 0.5
z_dims: [3, 2, 1, 2]
e_units: [64, 64, 64, 64, 64]
g_units: [64, 64, 64, 64, 64]
h_units: [64, 32, 8]
f_units: [64, 32, 8]
dz_units: [64, 32, 8]
fit_egm_n_iter: 50000
lr: 0.0002
g_d_freq: 5
fit_epochs: 200
fit_epochs_per_eval: 10
fit_batch_size: 64
lr_theta: 0.0001
lr_z: 0.0001
outcome_to_particles_weight: 0.01
iv_mc_samples: 1000
eval_mc_samples: 1000
egm_num_warm_starts: 10
structural_map_steps: 1000
structural_map_lr: 0.0001
structural_methods: [map]
mcmc_num_chains: 4
mcmc_production_warmup_steps: 2000
mcmc_production_draws: 5000
